services:
  useraccount:
    container_name: ${IMAGE_NAME}-container
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    ports:
      - "3000:3000"  # host:container
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:7
    container_name: redis-container
    volumes:
      - redis-data:/data
    # 포트를 외부에 노출하지 않음 (보안용)

volumes:
  redis-data:
